### ISSUE TITLE
Dazn addon crash on Fire TV 

### ISSUE THREAD

**Issue by dontknowcris** [JinRonin/plugin.video.dazn#5] opened 2018-08-27 18:22 UTC
In Amazon Fire TV, the addon works properly just with alpha 1, with the other kodi 18 releases, the entire software crashes and with the use of alpha 1, there's the problem of wrong connection with CDNs

**Comment by anthonytex** [comment] 2018-08-27 18:42
It's not an addon fault but it should be caused by inputstream see https://github.com/peak3d/inputstream.adaptive/issues/176

**Comment by JinRonin** [comment] 2018-08-28 10:18
Yes, this is not addon related.
What do you mean with wrong cdn conntection? Alpha 1 should be good to go, ive implemented an compatibility mode for older versions that is enabled by default.

**Comment by dontknowcris** [comment] 2018-08-28 11:00
The wrong cdn connection is releated with an error due to xml link in alpha 1, but that problem can be solved with dazn 1.2.0-temp, instead I think crashes are releated with latest version of inputstream

**Comment by JinRonin** [comment] 2018-08-31 14:01
Should be fixed with https://github.com/peak3d/inputstream.adaptive/commit/997abf6c9d3f60a0ebcff841fd31062fb7eb02c8

**Closed by JinRonin** 2018-08-31 14:01 UTC

**Comment by dontknowcris** [comment] 2018-08-31 14:05
It works with vod, kodi doesn't crash anymore. Tonight I will try with live events

**Comment by dontknowcris** [comment] 2018-09-03 14:01
I write here the same post I left on the inputstream page

sorry if I cannot post any crash logs here, but I cannot find them on the fire tv stick
by the way, at this time, kodi always crash at the same time in some streams running on dazn addon.
when I try to watch a football match on demand, the match starts without any problem, but after some minutes there's a buffering and the video freezes. if I try to stop the playback and going back to football matches list, then kodi crashes and goes back to the home of fire tv. and if I try to play again the same vod, the video always freezes at the same point then the previous one
same issue with live events (obviously in this case, the crash moment is different, depending on when I try to play a match)
